apiVersion: v1
kind: Secret
metadata:
  name: weather-app-secrets
  namespace: weather-app
type: Opaque
data:
    REACT_APP_OPENWEATHERMAP: ZDAwODQzY2Y5ZDcxNzQ5NzBkYmI5YjcyZGU5YzJhZGYK
    REACT_APP_OPENCAGEDATA: M2U4NTFiYWFlZGM5NDU0YWE5ZTQ1NjBmNzc2MzhlZGUK
    REACT_APP_POSITIONSTACK: YzJhOTRiM2VjNzBhNTBmNGUwYWY1MzZjZDQyNmQxMDAK